### ISSUE TITLE
Bind this missing?

### ISSUE THREAD

**Issue by rooi** [luc-ass/homebridge-evohome#104]
Hi,

I just got the following error:

TypeError: Cannot read property 'log' of undefined
    at /usr/lib/node_modules/homebridge-evohome/index.js:617:14
    at _rejected (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:864:24)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:890:30
    at Promise.when (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:808:41)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Thanks!

**Comment by luc-ass** [comment]
Thanks again for fixing this! 🚀 

Your request has been merged as of v0.8.8.
