### ISSUE TITLE
SET handler returned write response value, though the characteristic doesn't support write response

### ISSUE THREAD

**Issue by PuzzledUser** [luc-ass/homebridge-evohome#105]
Hey Lucas, I noticed a non-breaking error when using debug mode for something else:

```
[30/12/2021, 20:35:32] [Evohome] Renewed Honeywell API authentication token!
[30/12/2021, 20:40:00] [Evohome] Target temperature for XX's Thermostat is 17°
[30/12/2021, 20:40:00] [Evohome] HEAT or COOL selected, previous state AUTO, HEAT or COOL. Doing nothing.
[30/12/2021, 20:40:00] [Evohome] Request to set target temperature to 17.5
[30/12/2021, 20:40:01] [homebridge-evohome] Characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[30/12/2021, 20:40:01] [homebridge-evohome] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1699:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at EvohomeThermostatAccessory.setTargetTemperature (/usr/local/lib/node_modules/homebridge-evohome/index.js:905:5)
    at TargetTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1668:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1666:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
[30/12/2021, 20:40:06] [Evohome] The current time is 20:40:06
[30/12/2021, 20:40:06] [Evohome] Schedule points for today (Thursday)
[30/12/2021, 20:40:06] [Evohome] - 06:50:00
[30/12/2021, 20:40:06] [Evohome] - 07:10:00
[30/12/2021, 20:40:06] [Evohome] - 08:10:00
[30/12/2021, 20:40:06] [Evohome] - 18:00:00
[30/12/2021, 20:40:06] [Evohome] - 22:00:00 -> next change
[30/12/2021, 20:40:06] [Evohome] Setting target temperature for XX's Thermostat to 17.5° until 22:00:00
[30/12/2021, 20:40:07] [Evohome] Successfully changed temperature!
[30/12/2021, 20:40:07] [Evohome] { id: '1751580607' }
[30/12/2021, 20:49:30] [Evohome] Updating: XX's currentTempChange from: 17 to: 17.5
[30/12/2021, 21:04:45] [Evohome] Target temperature for XX's Thermostat is 17.5°
[30/12/2021, 21:04:45] [Evohome] Current temperature of XX's Thermostat is 17.5°
```

A few other plugins have had (and fixed) this in the last year... One for the New Year! Take care 😊

**Comment by luc-ass** [comment]
Hey there. I am trying to follow up on some issues. Can you point me to other plugins (preferably the commit) that changed this behaviour?

Thanks for reporting the issue!

**Comment by luc-ass** [comment]
I read up a little on this message and it seems this is for debugging only. Onzu and Donavan both didn't mind - so I don't 😆
