### ISSUE TITLE
Cannot read property 'userID' of undefined

### ISSUE THREAD

**Issue by tim-payne** [luc-ass/homebridge-evohome#12]
I've just installed homebridge and homebridge-evohome on my mac and created config.json.

when invoking home bridge i get the following error, could you possibly advise what I've omitted to do?

[11/24/2016, 1:14:55 PM] Loading 1 platforms...
[11/24/2016, 1:14:55 PM] [Evohome] Initializing Evohome platform...
[11/24/2016, 1:14:55 PM] [Evohome] Logging into Evohome...
[11/24/2016, 1:14:55 PM] [Evohome] Error during Login: TypeError: Cannot read property 'userID' of undefined
    at new UserInfo (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:6:23)
    at new Session (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:26:18)
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:190:11
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by luc-ass** [comment]
Could you please post your config.json (don't forget to anonymize your user/pass)

**Comment by tim-payne** [comment]
I ran it thru JSONLINT and it appears ok.  Its as follows:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform": "Evohome",
            "name" : "Evohome",
            "username" : "xxx@yyy.com",
            "password" : "xyzabc",
            "appId" : "91db1612-73fd-4500-91b2-e63b069b185c"
        }
    ]
}

**Comment by tim-payne** [comment]
Hi Lucas, any suggestions?  
Thanks.

**Comment by luc-ass** [comment]
Hm,perhaps an old version of node? Please have a look at the recommendations of homebridge itself and install one of these versions.

I have v4.2.1 installed

**Comment by tim-payne** [comment]
Unfortunately home bridge will no longer install with V4.2.1, it needs 4.3.2 now as a minimum.
I installed 4.3.2 but unfortunately I still get the same error i.e. on installing homebridge-evohome
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
and when running homebridge:
Error during Login: TypeError: Cannot read property 'userID' of undefined

Would you possibly have any other suggestions? Am very keen to get this working

**Comment by luc-ass** [comment]
Well. I just saw that I hat the above error as well. Wasn't a problem for me so we need to keep on searching... what country is your account registered to?

**Comment by tim-payne** [comment]
I'm registered in the U.K. Thanks for your help

**Comment by luc-ass** [comment]
Sorry to ask the basics. Could you please try to log into https://international.mytotalconnectcomfort.com/Account/Login ? Please copy the credentials you used above to verify they are working.

The userID-part of the JSON makes me think something does not work with the login itself.

**Comment by tim-payne** [comment]
I've just installed it on another mac and this time it worked first time.  Many thanks!

**Comment by luc-ass** [comment]
Still no idea why... :D I'll mark this as closed....

**Comment by gekkie** [comment]
You might want to update the readme doc. The appId is not optional and it's needs to be that uuid, I generated my own uuid and userId issues.

**Comment by luc-ass** [comment]
Haha, it is actually optional - it's just that you can not set it to something random. I'll remove it from the confit altogether ;)

**Comment by plangin** [comment]
I have the same issue.... homebridge-evohome used to work reliable 2 days with a german account. Now on almost every temperature change, I get this:

[2018-1-11 08:09:01] [Evohome] Evohome Failed: TypeError: Cannot read property 'userID' of undefined                             
    at new UserInfo (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:6:24)                                         
    at new Session (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:26:18)                                         
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:194:11                                                      
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)                                    
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)                     
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)               
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44                                                 
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)                                         
    at _combinedTickCallback (internal/process/next_tick.js:131:7)                                                               
    at process._tickCallback (internal/process/next_tick.js:180:9)

My config.json:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "Evohome",
            "name" : "Evohome",
            "username" : "my@mail.de",
            "password" : "*****",
            "appId" : "91db1612-73fd-4500-91b2-e63b069b185c"
        }
    ]
}

Any ideas? :-/

**Comment by brownad** [comment]
Hi although it’s a great plugin it’s not up to date or fully there with features. I’ve tried and still using the homeassistant setup with their homebridge-homeassistant it has support for Evohome within the HASS itself. You can setup on the same box that runs homebridge. Might be worth the effort if you want something a bit more rounded.

**Comment by fredericvl** [comment]
For the one's who are interested, I'm currently working on a fork of homebridge-evohome that uses a newer version of Honeywell API (with more options)

**Comment by tim-payne** [comment]
You couldn't possibly add support for more than one Evohome controller could you? :-)

**Comment by brownad** [comment]
That would be cool, planning to merge back to here?

**Comment by plangin** [comment]
@brownad 
Thank you for the tip. Accidentally I found the explanation for the issue:

"Note: Scan interval is expressed in seconds. Omitting scan_interval may result in too-frequent polling and cause you to rate-limited by Honeywell."

So I assume, when changing the temperature too quick, Honewell's server does reject the request. This does also explain why it used to work fine in the beginning. During testing, I only used Siri commands to set temps, now I started using the Elgato EVE app, where you can change set temperatures quick by ticking several times per second on up or down buttons.

Idea for fix: Introduce also some kind of interval / delay to avoid server rejections. I will open a new issue.

**Comment by fredericvl** [comment]
@tim-payne I will have a look at multiple location support, but can't promise anything ;-)
@brownad Definitely planning to merge back once it's complete!

**Comment by brownad** [comment]
Brilliant you have a few fans and thanks to @luc-ass for starting this project

**Comment by rooi** [comment]
Great! I also found this https://github.com/simont77/fakegato-history
I was hoping to include it in this version as well, but perhaps I should wait untill the merge...
