### ISSUE TITLE
Not all rooms can we changed

### ISSUE THREAD

**Issue by JeroenCloo** [luc-ass/homebridge-evohome#14]
Hi, I have 6 rooms setup in my Evohome system. All 6 rooms are shown in the HomeKit app.
Unfortunately only 2 (' Woonkamer'  and ' Badkamer kids' ) of them seems to work. 4 of them show are not responding.

On the raspberry Pi I can see that all 6 rooms are read:

[12/19/2016, 9:44:39 AM] [Evohome] Current temperature of Speelkamer Thermostat is 12.55°
[12/19/2016, 9:44:39 AM] [Evohome] getCurrentHeatingCooling
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Speelkamer Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Speelkamer Thermostat is 5°
[12/19/2016, 9:44:39 AM] [Evohome] getCurrentHeatingCooling
[12/19/2016, 9:44:39 AM] [Evohome] Current temperature of Charlotte Thermostat is 11.13°
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Charlotte Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Charlotte Thermostat is 5°
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Badkamer kids Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Badkamer kids Thermostat is 10°
[12/19/2016, 9:44:39 AM] [Evohome] Current temperature of Badkamer kids Thermostat is 13.63°
[12/19/2016, 9:44:39 AM] [Evohome] getCurrentHeatingCooling
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Woonkamer Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Woonkamer Thermostat is 21°
[12/19/2016, 9:44:39 AM] [Evohome] Current temperature of Woonkamer Thermostat is 20.29°
[12/19/2016, 9:44:39 AM] [Evohome] getCurrentHeatingCooling
[12/19/2016, 9:44:39 AM] [Evohome] Current temperature of Badkamer Thermostat is 14.09°
[12/19/2016, 9:44:39 AM] [Evohome] getCurrentHeatingCooling
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Badkamer Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Badkamer Thermostat is 5°
[12/19/2016, 9:44:39 AM] [Evohome] Temperature unit for Sophie Thermostat is set to Celsius
[12/19/2016, 9:44:39 AM] [Evohome] Device type is: EMEA_ZONE. Target temperature should be there.
[12/19/2016, 9:44:39 AM] [Evohome] Target temperature for Sophie Thermostat is 5°
[12/19/2016, 9:44:40 AM] [Evohome] Current temperature of Sophie Thermostat is 11.42°
[12/19/2016, 9:44:40 AM] [Evohome] getCurrentHeatingCooling

Any ideas?

**Comment by luc-ass** [comment]
Strange, is this consistend with different apps? I noticed, that the Apple Home App sometimes ignores updates.

**Comment by JeroenCloo** [comment]
It appears that the target temperature must be 10 degrees or higher. A target temperature below that value results in the behaviour I mentioned in my previous post.

**Comment by luc-ass** [comment]
I.e. HomeKit doesn't understand values below 10 degrees? That would be a critical flaw...

**Comment by luc-ass** [comment]
Okay, I had a look into HAP NodeJS and found the following for `Characteristic.TargetTemperature`:
```
[...]
unit: Characteristic.Units.CELSIUS,
maxValue: 38,
minValue: 10,
minStep: 0.1,
[...]
```
I'll check how to fix the problem!

**Comment by brownad** [comment]
I have same problem. Is there a way to override this directly or needs a PR on HAP?

**Comment by brownad** [comment]
Very cool :+1:

**Comment by luc-ass** [comment]
Okay - took me some time but I implemented it - could someone try it out? I won't be able for the days to come...

**Comment by brownad** [comment]
Yes I'd be happy to try tonight.

I have 8 rooms

**Comment by brownad** [comment]
Wasn't happy:

2/22/2017, 8:14:49 PM] [Evohome] Evohome Failed: TypeError: Cannot read property 'CurrentTemperature' of undefined
    at Object.getServices (/usr/local/lib/node_modules/homebridge-evohome/index.js:327:26)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-evohome/index.js:81:5)
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by brownad** [comment]
The above was pulling it down directly. I had to revert back

**Comment by luc-ass** [comment]
Sorry hearing that. I'll gave it another shot... Let's see wether this works. Can't really wrap my head around the things nfarina did there to modify proprietary values...

**Comment by brownad** [comment]
That's fine easy to check and rollback

I'll take another look later.

Btw was there any useful ideas in the waterstock api to set temp to next schedule?

**Comment by brownad** [comment]
same:

[2/23/2017, 4:35:59 PM] [Evohome] Evohome Failed: TypeError: Cannot read property 'CurrentTemperature' of undefined
    at Object.getServices (/usr/local/lib/node_modules/homebridge-evohome/index.js:327:26)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-evohome/index.js:81:5)
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9

**Comment by luc-ass** [comment]
As it should be working with the latest merge I will close this threat

**Comment by brownad** [comment]
Is it merged yet?

**Comment by luc-ass** [comment]
now

**Comment by brownad** [comment]
Is the latest pushed to NPM yet?

Didn't see any changes come through only the merge in GH

**Comment by brownad** [comment]
What is eyebrows minimum temp set to?

I tested the off feature on evohome to 5 degrees, it took out the plugin straight away. Is it still set as 10?

**Comment by luc-ass** [comment]
Sorry to hear that. Did you update from npm?

As far as I can see the temperature is set to 0 for target temperature and current temperature.

**Comment by brownad** [comment]
Yep I did but will triple check later..

**Comment by brownad** [comment]
I checked, am running 0.1.6 and its still set to 10, cannot lower it.  also crashes if you turn Evhome to "off" - which sets temp to 5 degrees

**Comment by luc-ass** [comment]
check wether it works now. Version was bumped to 0.2.0

**Comment by luc-ass** [comment]
Just checked this again. It now works in v0.3.1. 

Siri can change the temperature to 5°
```
[1/26/2018, 6:31:47 PM] [Evohome] Schedule points for today (Friday)                                     
[1/26/2018, 6:31:47 PM] [Evohome] - 08:00:00                                                             
[1/26/2018, 6:31:47 PM] [Evohome] - 23:00:00 -> next change                                              
[1/26/2018, 6:31:47 PM] [Evohome] Setting target temperature for Arbeitszimmer Thermostat to 5° until 23:00:00                                                                                                    
[1/26/2018, 6:31:48 PM] [Evohome] Successfully changed temperature!                                      
[1/26/2018, 6:31:48 PM] [Evohome] { id: '7703459' }   
```

Turning the heating off results in being ignored now. In the future I want to change that to 5° permanent/return to schedule.
```
[1/26/2018, 6:31:28 PM] [Evohome] attempted to change targetHeatingCooling: 0 - not yet implemented      

```
