### ISSUE TITLE
Hoobs plugin “Evohome” (0.11.0) does not work

### ISSUE THREAD

**Issue by keremicelli** [luc-ass/homebridge-evohome#166]
Hoobs plugin “Evohome” (0.11.0) does not work. Other plugins have no issues. Hoobs running on version 4.2.5 node version 16.15.1. Plugin configuration has not changed. Help much appreciated. Thanks in advance.
Persisting Log regarding the issue:

```
2/5/2024, 6:22:10 AMHoneywell Bridge starting
2/5/2024, 6:22:17 AMHoneywell BridgeLoaded plugin 'homebridge-evohome'
2/5/2024, 6:22:20 AMHoneywell BridgeERRORError initializing plugin 'homebridge-evohome'
2/5/2024, 6:22:20 AMHoneywell BridgeERROR/var/lib/hoobs/honeywellbridge/node_modules/googleapis/build/src/apis/compute/alpha.js:1 ���������������������
……..….. Repeating excessively ……….
��������������������� 
options = {}; SyntaxError: Invalid or unexpected token at Object.compileFunction (node:vm:352:18) at wrapSafe (node:internal/modules/cjs/loader:1033:15) at Module._compile (node:internal/modules/cjs/loader:1069:27) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.<anonymous> (/var/lib/hoobs/honeywellbridge/node_modules/googleapis/build/src/apis/compute/index.js:18:17) at Module._compile (node:internal/modules/cjs/loader:1105:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.<anonymous> (/var/lib/hoobs/honeywellbridge/node_modules/googleapis/build/src/apis/index.js:98:19)
2/5/2024, 6:22:20 AMHoneywell BridgeWARNINGNo plugins installed.
2/5/2024, 6:22:20 AMHoneywell BridgeLoading 1 platforms...
2/5/2024, 6:22:20 AMHoneywell BridgeBridge is running on port 51856.
```

**Comment by luc-ass** [comment]
Sorry to hear that. homebridge-evohome was originally written for homebridge and never tested nor optimised for Hoobs. I might not be able to fix this for you, as I don't have any compatible system. 
Has this plugin previously been running okay?

**Comment by keremicelli** [comment]
Hi Lucas, 

thank you very much for your prompt response. 
Much appreciated! ❤️ 

I’m quite surprised now because, check this out: 
https://plugins.hoobs.org/plugin/homebridge-evohome. 
Here, it is listed as a “HOOBS certified” plugin. 😊 (HOOBS is based on Homebridge.)

And yes, it’s been working fine with HOOBS for nearly a year now… Until it all very suddenly stopped doing so. Uninstalling and reinstalling doesn’t help. I consistently receive the same error message as above. 
I cleaned the cache, did restarts, etc. many times with no effect. 
All other plugins and bridges running on HOOBS do work reliably. And I have quite a few of them… Therefore - as you can imagine - I absolutely do not want to do a complete reset. 

If a straight fix for my issue is not possible, could you possibly recommend me an alternative way to integrate Honeywell (now Resideo) Evohome controls into Apple Home? Using HOOBS would of course be more preferable since I already manage several bridges with it.

Thank you very much!
Cheers
Kerem

**Comment by luc-ass** [comment]
The cause is gone in `1.0.0-beta.1`, though I have to be straight with you about
what that means for Hoobs.

**What was wrong.** Nothing in this plugin, and nothing about Evohome.
`fakegato-history`, which drew the Eve graphs, pulls in `fakegato-storage`, and
that file requires `./lib/googleDrive` — and with it the whole of `googleapis` —
unconditionally, at import time, even though this plugin only ever used
`storage: "fs"`. Your stack trace ends in `googleapis/build/src/apis/compute/alpha.js`
for that reason: a Google Cloud Compute API surface, loaded on a heating plugin,
because of a dependency of a dependency of a graph nobody asked for.

**What changed.** `fakegato-history` is now an optional dependency, imported
lazily and only when history is switched on. With `"history": false` it is never
imported and `googleapis` is never loaded. If it is not installed at all
(`npm install --omit=optional`), the plugin runs without history instead of
failing to start.

**The caveat.** `1.0.0` requires Homebridge 2 and Node 22, 24 or 26. Hoobs 4.2.5
on Node 16 cannot run it, so this fix will not reach you where you are. I have no
Hoobs system to test against and cannot promise anything about that platform —
the "HOOBS certified" badge on their site is theirs, not mine.

Closing because the bug is fixed in the code. @keremicelli, if you move to
Homebridge 2 and hit anything, please open a new issue.
