### ISSUE TITLE
Cannot read properties of undefined (reading 'DATA')

### ISSUE THREAD

**Issue by jaketame** [luc-ass/homebridge-evohome#173]
[9/30/2024, 12:01:34 PM] [Evohome] Error getting system mode status:
 TypeError: Cannot read properties of undefined (reading 'DATA')
    at new S2R1Characteristic (/opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/fakegato-history/fakegato-history.js:78:36)
    at FakeGatoHistory.addCharacteristic (/opt/homebrew/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:518:57)
    at FakeGatoHistory.registerEvents (/opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/fakegato-history/fakegato-history.js:481:10)
    at new FakeGatoHistory (/opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/fakegato-history/fakegato-history.js:400:9)
    at new EvohomeThermostatAccessory (/opt/homebrew/lib/node_modules/homebridge-evohome/index.js:716:25)
    at EvohomePlatform.<anonymous> (/opt/homebrew/lib/node_modules/homebridge-evohome/index.js:203:41)
    at _fulfilled (/opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/q/q.js:854:54)
    at /opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:13)
    at /opt/homebrew/lib/node_modules/homebridge-evohome/node_modules/q/q.js:624:44

**Comment by luc-ass** [comment]
Sorry, I don't want to be rude, but this is not a helpful request. This error is known and a result of problems with the Honeywell server, your internet connection or DNS response.
