### ISSUE TITLE
syntax error token position 0 at jsonwith node 10.4.1

### ISSUE THREAD

**Issue by sapgitest** [luc-ass/homebridge-evohome#40]
plugin has a problem with node 10.4.1 (which i had to upgrade because of an another plugin). 
at process._tickCallback (internal/process/next_tick.js:63:19)
    at endReadableNT (_stream_readable.js:1081:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-evohome/node_modules/request/request.js:929:12)
    at Request.emit (events.js:187:15)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-evohome/node_modules/request/request.js:978:14)
    at Request.emit (events.js:182:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-evohome/node_modules/request/request.js:121:22)
    at Request._callback (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:254:29)
    at JSON.parse (<anonymous>)
[6/16/2018, 2:13:29 PM] [Evohome] Evohome Failed: SyntaxError: Unexpected token < in JSON at position 0
[6/16/2018, 2:13:28 PM] [Evohome] Logged into Evohome!

**Comment by luc-ass** [comment]
Strange. Have you got to the bottom of this?

**Comment by luc-ass** [comment]
ok, I'll mark this as closed as there has been no feedback.
