### ISSUE TITLE
Cannot read property 'temperatureControlSystems' of undefined

### ISSUE THREAD

**Issue by RienduPre** [luc-ass/homebridge-evohome#43]
Any Idea what might cause this error ?

Sep 26 10:08:57 homebridge homebridge[8079]: [2018-9-26 10:08:57] [Evohome] Evohome Failed: TypeError: Cannot read property 'temperatureControlSystems' of undefined
Sep 26 10:08:57 homebridge homebridge[8079]:     at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:137:49
Sep 26 10:08:57 homebridge homebridge[8079]:     at Function.map (/usr/local/lib/node_modules/homebridge-evohome/node_modules/lodash/dist/lodash.js:3509:27)
Sep 26 10:08:57 homebridge homebridge[8079]:     at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:125:18
Sep 26 10:08:57 homebridge homebridge[8079]:     at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
Sep 26 10:08:57 homebridge homebridge[8079]:     at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
Sep 26 10:08:57 homebridge homebridge[8079]:     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
Sep 26 10:08:57 homebridge homebridge[8079]:     at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
Sep 26 10:08:57 homebridge homebridge[8079]:     at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
Sep 26 10:08:57 homebridge homebridge[8079]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Sep 26 10:08:57 homebridge homebridge[8079]:     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by luc-ass** [comment]
I pushed a new version to npm. Can you check wether it is working now?

**Comment by ChampMart** [comment]
Hello,

i have the same problem:

[11/15/2018, 9:40:00 PM] [Evohome] Evohome Failed: TypeError: Cannot read property 'temperatureControlSystems' of undefined
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:137:48
    at Function.map (/usr/local/lib/node_modules/homebridge-evohome/node_modules/lodash/dist/lodash.js:3509:27)
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:125:18
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any idea to fix it? 

I get the following warnigs if i install the plugin:

pi@raspberrypi:~ $ sudo npm i homebridge-evohome@latest -g
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
+ homebridge-evohome@0.6.1
updated 1 package in 6.102s

**Comment by luc-ass** [comment]
Can you try installing it like this: `sudo npm install -g --unsafe-perm homebridge`

**Comment by ChampMart** [comment]
No effect: 

pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.45
updated 1 package in 6.29s
pi@raspberrypi:~ $ homebridge
[11/15/2018, 9:51:21 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/15/2018, 9:51:21 PM] ---
[11/15/2018, 9:51:22 PM] Loaded plugin: homebridge-evohome
[11/15/2018, 9:51:23 PM] Registering platform 'homebridge-evohome.Evohome'
[11/15/2018, 9:51:23 PM] ---
[11/15/2018, 9:51:23 PM] Loading 1 platforms...
[11/15/2018, 9:51:23 PM] [Evohome] Initializing Evohome platform...
[11/15/2018, 9:51:23 PM] [Evohome] Logging into Evohome...
[11/15/2018, 9:51:23 PM] Loading 0 accessories...
[11/15/2018, 9:51:24 PM] [Evohome] Logged into Evohome!
[11/15/2018, 9:51:25 PM] [Evohome] Evohome Failed: TypeError: Cannot read property 'temperatureControlSystems' of undefined
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:137:48
    at Function.map (/usr/local/lib/node_modules/homebridge-evohome/node_modules/lodash/dist/lodash.js:3509:27)
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:125:18
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
pi@raspberrypi:~ $

**Comment by luc-ass** [comment]
What kind of devices do you use in your home?

**Comment by luc-ass** [comment]
oh sorry - forgot to change something:
`sudo npm install -g --unsafe-perm homebridge-evohome`

**Comment by ChampMart** [comment]
Sorry: 
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-evohome
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
+ homebridge-evohome@0.6.1
updated 1 package in 10.197s

pi@raspberrypi:~ $ homebridge
[11/15/2018, 9:54:42 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/15/2018, 9:54:42 PM] ---
[11/15/2018, 9:54:43 PM] Loaded plugin: homebridge-evohome
[11/15/2018, 9:54:44 PM] Registering platform 'homebridge-evohome.Evohome'
[11/15/2018, 9:54:44 PM] ---
[11/15/2018, 9:54:44 PM] Loading 1 platforms...
[11/15/2018, 9:54:44 PM] [Evohome] Initializing Evohome platform...
[11/15/2018, 9:54:44 PM] [Evohome] Logging into Evohome...
[11/15/2018, 9:54:44 PM] Loading 0 accessories...
[11/15/2018, 9:54:45 PM] [Evohome] Logged into Evohome!
[11/15/2018, 9:54:46 PM] [Evohome] Evohome Failed: TypeError: Cannot read property 'temperatureControlSystems' of undefined
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:137:48
    at Function.map (/usr/local/lib/node_modules/homebridge-evohome/node_modules/lodash/dist/lodash.js:3509:27)
    at /usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:125:18
    at _fulfilled (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/homebridge-evohome/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
pi@raspberrypi:~ $

Devices are the Starter Paket (THR993RT), the Gateway (RFG100 ) and three THR092HRT

**Comment by ChampMart** [comment]
Hi luc-ass,

are you trying to fix the bug or is one of my devices or my configuration the cause of the error? Is there anything I can do to help you?

**Comment by luc-ass** [comment]
I am not sure what causes the problem. What version of npm and nodejs are you running.

**Comment by ChampMart** [comment]
npm is version 6.4.1 node is version 6.10.0 - I try to install homekit again new but same problem!

**Comment by ChampMart** [comment]
I could find out the reason for the error. There was a second location created no devices were assigned! After deleting the location online eyerthing works fine!
