### ISSUE TITLE
Suddenly crashing?

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/homebridge-evohome#5]
Did Honeywell change something? homebridge-evohome is suddenly crashing homebridge:

Apr 20 22:45:35 raspberrypi homebridge[1986]: ^
Apr 20 22:45:35 raspberrypi homebridge[1986]: SyntaxError: Unexpected token <
Apr 20 22:45:35 raspberrypi homebridge[1986]: at Object.parse (native)
Apr 20 22:45:35 raspberrypi homebridge[1986]: at Request._callback (/usr/local/lib/node_modules/homebridge-evohome/lib/evohome.js:181:26)
Apr 20 22:45:35 raspberrypi homebridge[1986]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-evohome/node_modules/request/request.js:121:22)
Apr 20 22:45:35 raspberrypi homebridge[1986]: at emitTwo (events.js:87:13)

**Comment by luc-ass** [comment]
problem solved. The URL for the API (v1) has been shut down. New URL works just like before. Happy using... (update to >0.1.1 to use it).
