### ISSUE TITLE
homebridge fails

### ISSUE THREAD

**Issue by ja-besse** [luc-ass/homebridge-evohome#55]
After updating homebridge and homebridge-evohome:

[jeroen@pine ~]$ sudo npm install -g homebridge
[sudo] wachtwoord voor jeroen: 
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
/usr/lib
└── homebridge@0.4.50 

[jeroen@pine ~]$ sudo npm install -g homebridge-evohome
/usr/lib
└── homebridge-evohome@0.6.3 

And starting
[jeroen@pine ~]$ sudo systemctl restart homebridge

It eventually fails, with this in /var/log/messages:

Jan 29 21:30:22 pine homebridge: [1/29/2020, 9:30:22 PM] Homebridge is running on port 51826.
Jan 29 21:30:24 pine homebridge: [1/29/2020, 9:30:24 PM] TypeError: "list" argument must be an Array of Buffers
Jan 29 21:30:24 pine homebridge: at Function.Buffer.concat (buffer.js:314:13)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
Jan 29 21:30:24 pine homebridge: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 29 21:30:24 pine homebridge: at emitNone (events.js:86:13)
Jan 29 21:30:24 pine homebridge: at IncomingMessage.emit (events.js:185:7)
Jan 29 21:30:24 pine homebridge: at endReadableNT (_stream_readable.js:978:12)
Jan 29 21:30:24 pine homebridge: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jan 29 21:30:24 pine homebridge: [1/29/2020, 9:30:24 PM] Got SIGTERM, shutting down Homebridge...
Jan 29 21:30:24 pine homebridge: [1/29/2020, 9:30:24 PM] TypeError: "list" argument must be an Array of Buffers
Jan 29 21:30:24 pine homebridge: at Function.Buffer.concat (buffer.js:314:13)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
Jan 29 21:30:24 pine homebridge: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 29 21:30:24 pine homebridge: at emitNone (events.js:86:13)
Jan 29 21:30:24 pine homebridge: at IncomingMessage.emit (events.js:185:7)
Jan 29 21:30:24 pine homebridge: at endReadableNT (_stream_readable.js:978:12)
Jan 29 21:30:24 pine homebridge: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jan 29 21:30:24 pine homebridge: [1/29/2020, 9:30:24 PM] TypeError: "list" argument must be an Array of Buffers
Jan 29 21:30:24 pine homebridge: at Function.Buffer.concat (buffer.js:314:13)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
Jan 29 21:30:24 pine homebridge: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 29 21:30:24 pine homebridge: at emitNone (events.js:86:13)
Jan 29 21:30:24 pine homebridge: at IncomingMessage.emit (events.js:185:7)
Jan 29 21:30:24 pine homebridge: at endReadableNT (_stream_readable.js:978:12)
Jan 29 21:30:24 pine homebridge: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jan 29 21:30:24 pine homebridge: [1/29/2020, 9:30:24 PM] TypeError: "list" argument must be an Array of Buffers
Jan 29 21:30:24 pine homebridge: at Function.Buffer.concat (buffer.js:314:13)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
Jan 29 21:30:24 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
Jan 29 21:30:24 pine homebridge: at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
Jan 29 21:30:24 pine homebridge: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 29 21:30:24 pine homebridge: at emitNone (events.js:86:13)
Jan 29 21:30:24 pine homebridge: at IncomingMessage.emit (events.js:185:7)
Jan 29 21:30:24 pine homebridge: at endReadableNT (_stream_readable.js:978:12)
Jan 29 21:30:24 pine homebridge: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jan 29 21:30:25 pine homebridge: [1/29/2020, 9:30:25 PM] TypeError: "list" argument must be an Array of Buffers
Jan 29 21:30:25 pine homebridge: at Function.Buffer.concat (buffer.js:314:13)
Jan 29 21:30:25 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
Jan 29 21:30:25 pine homebridge: at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
Jan 29 21:30:25 pine homebridge: at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
Jan 29 21:30:25 pine homebridge: at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
Jan 29 21:30:25 pine homebridge: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 29 21:30:25 pine homebridge: at emitNone (events.js:86:13)
Jan 29 21:30:25 pine homebridge: at IncomingMessage.emit (events.js:185:7)
Jan 29 21:30:25 pine homebridge: at endReadableNT (_stream_readable.js:978:12)
Jan 29 21:30:25 pine homebridge: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jan 29 21:30:29 pine systemd: homebridge.service: main process exited, code=exited, status=143/n/a
Jan 29 21:30:29 pine systemd: Unit homebridge.service entered failed state.
Jan 29 21:30:29 pine systemd: homebridge.service failed.

Nodejs is version: nodejs-6.17.1-1.el7.aarch64

Is this a homebridge or a homebridge-evohome issue?

**Comment by ja-besse** [comment]
The nodes on my CentOS 7 system (from EPEL) seems to be too old.

Documenting for other users who might run into this:

Removed it:
`sudo yum remove nodejs npm`

Downloaded a decent version from https://nodejs.org/en/download/

Installed it:
`sudo tar --strip-components 1 -xvf node-v* -C /usr/local`
