### ISSUE TITLE
Sudden errors occurring - Error during Login: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by cjastennett** [luc-ass/homebridge-evohome#56]
Hi,

started getting this error out of the blue:

[4/24/2020, 10:44:13 AM] [Evohome] Error during Login: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/homebridge/node_modules/homebridge-evohome/lib/evohome.js:289:29)
    at Request.self.callback (/homebridge/node_modules/homebridge-evohome/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-evohome/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-evohome/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

I checked my JSON confg file - all is good and nothing has changes, There are no erroneous "<" symbols, and my user ID and password is still there and still valid, Rebooting and restarting has no effect.

Thanks for any assistance you can provide.

cheers

**Comment by KLucky13** [comment]
I got he same issues, the service of evohome i currently down. The original app also does not work and also online on their website I can no longer login. Which can happen. What is not ok, is that my entire homebridge is down because off it. Nothing else works anymore because the evohome plugin stopped working. This needs to be looked at

**Comment by cjastennett** [comment]
OK - thanks for the update. It would seem then that the error handling in this plug is not contained and handled well, so it is crashing the the whole of the homebridge service. It would be great if this could be resolved.

**Comment by KLucky13** [comment]
I'm also just a user, an update on the errorhandling needs to come from the creator of the plugin

**Comment by cjastennett** [comment]
Absolutely - not expecting you to fix it - sorry if that was inferred.

Interesting, a knock on effect of this plugin erroring was that the Alexa plugin also was failing to connect - so I wonder if there was a cross-pollination of error there due to some kind of unhandled error in the top level sockets/request capabilities. 

Anyway, is back up and running now, as the Honeywell/Evohome services are now back up.

**Comment by KLucky13** [comment]
Yes, mine is also back up and running. In my case my lights etc also stopped working due to this maintenance on the Evohome servers. So that's far from ideal. When the servers of evohome are under maintenance, it's ok/logical that they stop responding in homekit, but I would at least expect that the rest of my domotica keeps running :-)

**Comment by luc-ass** [comment]
Good point, I am in the middle of the verification process for Homebridge verified plug-ins. I will probably need to fix this anyway as part of the process so keep your eyes open for an update.

On a sidenote configuration is no possible via the config-ui-x interface.

**Comment by luc-ass** [comment]
Should be fixed as of v0.7.1. Please reopen this issue if you still encounter this issue.
