### ISSUE TITLE
Evohome cannot read property 'temperatureControlSystems' of undefined

### ISSUE THREAD

**Issue by domdtyler** [luc-ass/homebridge-evohome#64]
Hi there,

I've just set up a new HOOBS installation (v3.2.10) on a Raspberry Pi Model B Rev 2 and installed Homebridge-evohome. It's the only plugin on the system. Every time I try to login I get the following error:

`Evohome Failed: TypeError: Cannot read property 'temperatureControlSystems' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-evohome/lib/evohome.js:137:49
    at arrayMap (/home/hoobs/.hoobs/node_modules/lodash/lodash.js:639:23)
    at Function.map (/home/hoobs/.hoobs/node_modules/lodash/lodash.js:9580:14)
    at /home/hoobs/.hoobs/node_modules/homebridge-evohome/lib/evohome.js:125:18
    at _fulfilled (/home/hoobs/.hoobs/node_modules/q/q.js:787:54)
    at /home/hoobs/.hoobs/node_modules/q/q.js:816:30
    at Promise.promise.promiseDispatch (/home/hoobs/.hoobs/node_modules/q/q.js:749:13)
    at /home/hoobs/.hoobs/node_modules/q/q.js:557:44
    at flush (/home/hoobs/.hoobs/node_modules/q/q.js:108:17)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

This is often accompanied by:

`Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:100:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:201:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:575:27)
    at Server.publishBridge (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:193:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:53
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:9)
12/11/2020, 18:41:50 Got SIGTERM, shutting down Bridge...`

Any idea how I can fix this? Thank you!

**Comment by luc-ass** [comment]
Sounds like you did not get a valid response from the server. Has this problem been solved? Do you have special characters in your password?

**Comment by domdtyler** [comment]
Hi there, thanks for your response! Unfortunately, the Pi we were using has decided to have a fit and died. We’re replacing that, have removed all special characters from the evohome password, and will try again in due course. I’ll update you if the problem remains.

**Comment by domdtyler** [comment]
Hi, I'm now using Homebridge on macOS, and am having the same issues. I'm happy to provide any other information you might need.
