### ISSUE TITLE
Plugin takes a lot of time to start

### ISSUE THREAD

**Issue by Maykel1969** [luc-ass/homebridge-evohome#87]
Hi,

I just moved from Hoobs to Homebridge and I immediately noticed something I haven't seen before.
After every restart I see one or sometimes even 5 of the following warnings in the log.

------------------
[homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
------------------

Is this a real problem? Everything seems to work fine.

**Comment by luc-ass** [comment]
I have never seen this with my homebridge (which I recommend anyways). What kind of hardware are you running?

**Comment by PuzzledUser** [comment]
I've just seen this when my internet connection was down. Wifi still up, but no connectivity via router. The issue persisted for hours, even after I sorted my broadband issue. I had to restart Homebridge to fix, see below.

- Be nice if it realised the network was good again
- Be nice if it didn't block loading of Homebridge too.

```[28/04/2024, 19:56:41] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:57:01] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:57:21] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:57:41] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:58:01] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:58:21] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:58:36] [Homebridge UI] Homebridge restart request received
[28/04/2024, 19:58:36] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[28/04/2024, 19:58:36] [Homebridge UI] Sending SIGTERM to Homebridge
[28/04/2024, 19:58:37] Got SIGTERM, shutting down Homebridge...
[28/04/2024, 19:58:37] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (events.js:315:20)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[28/04/2024, 19:58:37] Got SIGTERM, shutting down child bridge process...
[28/04/2024, 19:58:41] [homebridge-evohome] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[28/04/2024, 19:58:42] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```
