### ISSUE TITLE
Evo Home Plugin Crashes HomeBridge Instance

### ISSUE THREAD

**Issue by neilpatel121** [luc-ass/homebridge-evohome#89]
So getting the error TypeError: Cannot read property 'log' of undefined regularly, this causes the homebridge instance to die, I’m currently running the evohome plugin in a seperate instance. After the plugin crashes it loses all the temp control accessories in homekit, after restart the accessories get added back to the default room. 

Two issues here I believe

1. The crashing of the plunging 
2. State of accessories not maintained, they are dynamically added and removed each time, maybe this is by design and the HB instance needs to be always running and cant be restarted, otherwise need to assign the accessories rooms again.

Stack trace.. 

[3/15/2021, 4:28:03 AM] [Evohome] Updating: Family Bath currentTempChange from: 21 to: 21.5
TypeError: Cannot read property 'log' of undefined
    at /usr/lib/node_modules/homebridge-evohome/index.js:617:14
    at _rejected (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:864:24)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:890:30
    at Promise.when (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:808:41)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
TypeError: Cannot read property 'log' of undefined
    at /usr/lib/node_modules/homebridge-evohome/index.js:617:14
    at _rejected (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:864:24)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:890:30
    at Promise.when (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:808:41)
    at /usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-evohome/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by luc-ass** [comment]
It seems that there is an error when loading your `locations` (i.e. homes in evohome). Have you got more than one home in evohome?

**Comment by PuzzledUser** [comment]
Just to comment, I've (not OP) got two locations and don't see this issue.

**Comment by luc-ass** [comment]
Hey @neilpatel121,
do you still encounter this bug with any regularity?
1. The crash seems to happen because there is some error with the session object. Sadly I cannot find anything wrong.
2. This should be solved soon. Issue #61 deals with this problem.

I will be closing this issue, but I am really interested in solving this for good!
