### ISSUE TITLE
'Target Temperature': characteristic was supplied illegal value

### ISSUE THREAD

**Issue by MikeMighty** [luc-ass/homebridge-evohome#94]
Hi there,

Not really a master or king with the codes. My homebridge works without issues, only the following gets spammed in the log:

[8/30/2021, 10:43:32 PM] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[8/30/2021, 10:43:32 PM] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[8/30/2021, 10:43:32 PM] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[8/30/2021, 10:43:32 PM] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.

Can or should i do anything about this?

**Comment by luc-ass** [comment]
That's a new one... I haven't found similar stuff in my logs. Anyone?

As an Explaination: It seems, that homebridge is not fond of accepting temperatures below 5 degrees. This is used as `off` in homebridge-evohome. Are some of your thermostats turned off? Can you set them to 10 °C and keep an eye on your logs?

**Comment by MikeMighty** [comment]
Yes, that seems to solve the problem. I had the system in off mode for the summer. The standard 5 degrees in off mode cant be set to 10 or higher it seems. So the only workarround is to not put evohome in off mode. 

Thanks for the reply.

**Comment by luc-ass** [comment]
Okay, now that we know what causes this bug, can you give me some context?

- Hardware you are running homebridge on
- OS and version on your system
- NPM/Node version
- Homebridge version
- Plugin version

**Comment by Barloew** [comment]
I get a similar error in my log:

`[homebridge-evohome] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.`

I am running Dockerized Homebridge on Synology hardware. 
_Alpine Linux (3.12.8)
Node.js v14.17.6
Npm v6.14.15
Homebridge v1.3.4 
homebridge-evohome v0.8.4_

in my case, I have two thermostats at 5°. This has never been been an issue before. What was new is that one of my thermostats ran out of battery. This thermostat created a log file entry with a temperature of undefined°. As soon as I replaced the battery, the issue was gone. 

Hope this helps. Thanks for the great plugin.

**Comment by luc-ass** [comment]
As a workaround you can set your system to "away" and set away to something like 12 degrees...

**Comment by MikeMighty** [comment]
Hardware you are running homebridge on: RPI3
    OS and version on your system: Alpine Linux (3.12.7) 
    NPM/Node version: v14.17.5 
    Homebridge version: homebridge-config-ui-x v4.41.2
    Plugin version: homebridge-evohome v0.8.3

**Comment by PuzzledUser** [comment]
FYI, I produced this error by setting OFF on the HEAT, COOL, AUTO control. My system has a configured min value of 10°C, hence it complained when 5°C was _selected_. Shortly later it noticed that 10°C was set as target. No great shakes...

```
[02/01/2022, 14:50:54] [Evohome] Current temperature of XX Thermostat is 15.5°
[02/01/2022, 14:50:54] [Evohome] Target temperature for XX Thermostat is 5°
[02/01/2022, 14:50:54] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[02/01/2022, 14:51:23] [Evohome] Updating: XX targetTempChange from: 5 to: 10
```

**Comment by SeaneyC** [comment]
I messed about with various combinations of 15, 10, and 5 degree settings
with away turned off and on, and wasn’t able to generate any errors like
the 2 users above


   - Hardware you are running homebridge on: 2GB rPi4
   - OS and version on your system: Raspbian GNU/Linux Bullseye (11)
   - NPM/Node version: v16.14.0
   - Homebridge version: v1.5.0
   - Plugin version: 0.9

**Comment by MikeMighty** [comment]
It produces the error in off-mode, system default 5 degrees. Away-mode gives no errors. 

 

 

[23/08/2022, 23:08:40] [Evohome] System mode Away is false

[23/08/2022, 23:08:40] [Evohome] System mode DayOff is false

[23/08/2022, 23:08:40] [Evohome] System mode HeatingOff is true

[23/08/2022, 23:08:40] [Evohome] System mode AutoWithEco is false

[23/08/2022, 23:08:40] [Evohome] System mode Custom is false

[23/08/2022, 23:08:43] [Evohome] Current temperature of Woonkamer Thermostat is 25°

[23/08/2022, 23:08:43] [Evohome] Target temperature for Woonkamer Thermostat is 5°

[23/08/2022, 23:08:43] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

[23/08/2022, 23:08:43] [Evohome] Current temperature of Madeleine Thermostat is 24°

[23/08/2022, 23:08:43] [Evohome] Target temperature for Madeleine Thermostat is 5°

[23/08/2022, 23:08:43] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

[23/08/2022, 23:08:43] [Evohome] Current temperature of Hobbykamer Thermostat is 24.5°

[23/08/2022, 23:08:43] [Evohome] Target temperature for Hobbykamer Thermostat is 5°

[23/08/2022, 23:08:43] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

[23/08/2022, 23:08:43] [Evohome] Current temperature of Zolder Thermostat is 25°

[23/08/2022, 23:08:43] [Evohome] Target temperature for Zolder Thermostat is 5°

[23/08/2022, 23:08:43] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

[23/08/2022, 23:08:43] [Evohome] Current temperature of Slaapkamer Thermostat is 25°

[23/08/2022, 23:08:43] [Evohome] Target temperature for Slaapkamer Thermostat is 5°

[23/08/2022, 23:08:43] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

 

 

Van: SeaneyC ***@***.***> 
Verzonden: dinsdag 23 augustus 2022 22:43
Aan: luc-ass/homebridge-evohome ***@***.***>
CC: MikeMighty ***@***.***>; Author ***@***.***>
Onderwerp: Re: [luc-ass/homebridge-evohome] 'Target Temperature': characteristic was supplied illegal value (#94)

 

I messed about with various combinations of 15, 10, and 5 degree settings
with away turned off and on, and wasn’t able to generate any errors like
the 2 users above


- Hardware you are running homebridge on: 2GB rPi4
- OS and version on your system: Raspbian GNU/Linux Bullseye (11)
- NPM/Node version: v16.14.0
- Homebridge version: v1.5.0
- Plugin version: 0.9

**Comment by SeaneyC** [comment]
My bad. I tried with the system in off mode again with the default of 5
degrees and also bumped it to a default minimum of 10 degrees in off mode
on the controller and still wasn’t able to get it to produce anything
errant despite playing with Heat/Cool in the Home app and changing target
temps (which just get reset to follow the schedule, except then that
Heating Off is true so everything is just set to 5 degrees as the target.)


[23/08/2022, 22:58:25] [Evohome] System mode HeatingOff is true
[23/08/2022, 22:58:25] [Evohome] Target temperature for Living room
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Living room
Thermostat is 21.5°
[23/08/2022, 22:58:25] [Evohome] System mode DayOff is false
[23/08/2022, 22:58:25] [Evohome] Target temperature for Sean study
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Sean study
Thermostat is 23.5°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Guest bed 2
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Guest bed 2
Thermostat is 24°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Guest bed 1
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Guest bed 1
Thermostat is 23°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Kitchen Thermostat
is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Kitchen Thermostat
is 21.5°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Dressing area
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Dressing area
Thermostat is 22.5°
[23/08/2022, 22:58:25] [Evohome] System mode AutoWithEco is false
[23/08/2022, 22:58:25] [Evohome] Current temperature of Through room
Thermostat is 21.5°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Through room
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] System mode Away is false
[23/08/2022, 22:58:25] [Evohome] Current temperature of Landing Thermostat
is 24°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Landing Thermostat
is 5°
[23/08/2022, 22:58:25] [Evohome] System mode Custom is false
[23/08/2022, 22:58:25] [Evohome] Target temperature for Dining room
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Dining room
Thermostat is 21.5°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Master bedrm
Thermostat is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Master bedrm
Thermostat is 23.5°
[23/08/2022, 22:58:25] [Evohome] Target temperature for P study Thermostat
is 5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of P study Thermostat
is 22.5°
[23/08/2022, 22:58:25] [Evohome] Current temperature of Main bathrm
Thermostat is 24°
[23/08/2022, 22:58:25] [Evohome] Target temperature for Main bathrm
Thermostat is 5°

Set Bedroom to heat to 5 degrees using the home app which is what
puzzleduser was seeing

23/08/2022, 22:58:28] [Evohome] HEAT or COOL selected, previous state OFF,
cancelling override
[23/08/2022, 22:58:29] [Evohome] Cancelled override for Master bedrm
Thermostat (set to follow schedule)

This will set master bedroom to then just follow the schedule no matter
what was previously configured (eg any permanent or temporary temperature
settings set on the evohome controller or app) and when heatingoff goes
back to false, the thermostat will fall in line with the schedule set on
the controller.

**Comment by luc-ass** [comment]
Okay, thanks for your vigorous testing 😄 
@MikeMighty do your run your Homebridge in DEBUG-Mode?

**Comment by PuzzledUser** [comment]
I tried what proved it [previously](https://github.com/luc-ass/homebridge-evohome/issues/94#issuecomment-1003728959) and there is no error today. I reckon it was to do with OFF setting target to 5°C which is less than my minimum, but it's ok today. 

Then I tried a slightly different sequence in DEBUG mode and oops. 
```
[24/08/2022, 13:16:57] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[24/08/2022, 13:16:57] [homebridge-evohome] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at EvohomeThermostatAccessory.getTargetTemperature (/usr/local/lib/node_modules/homebridge-evohome/index.js:932:5)
    at TargetTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
```

To reproduce I:
- Set Off mode in Home
- Set Away mode in Comfort app (NB my [minimum](https://digitalassets.resideo.com/damroot/Original/10019/t87rf-ii-en2h50094157-014uk07.pdf) is 10°C)
- Opened Home app to trigger error (I guess it reads current state)
- Then cancel away mode (**and** increase target to above 10°C) to stop the error appearing.

**Comment by PuzzledUser** [comment]
Still there in homebridge-evohome v0.11.0

```
[19/03/2023, 21:56:36] [Evohome] Heating is set off for Puzzled's Thermostat (set to 5°)
[19/03/2023, 21:56:48] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[19/03/2023, 21:58:04] [homebridge-evohome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[19/03/2023, 22:01:48] [Evohome] Updating: Puzzled's targetTempChange from: 5 to: 13
```
Triggered on this occasion by asking the dumb Siri to _turn down_ the heating (it turned it _off_ instead).

**Comment by luc-ass** [comment]
Fixed in `1.0.0-beta.1` (`npm install -g homebridge-evohome@beta`, needs
Homebridge 2 and Node 22+).

Both halves of this thread had the same root: values were passed to HomeKit
without checking them first.

- **The 5 °C from "off".** Turning a zone off used to write a flat 5 °C, which
  HomeKit rejects on a system whose minimum is 10. Off is now expressed through
  `TargetHeatingCoolingState`, and every setpoint is clamped to the zone's own
  `setpointCapabilities` instead of a hard-coded range — so the value that goes
  out is one the system actually allows.
- **The `NaN` in @barloew's log.** A zone with a flat battery reports
  `isAvailable: false` and no temperature. 0.11.2 forwarded that straight
  through; it is now recognised and the zone keeps its last known reading rather
  than sending `NaN`. Since `beta.1` an empty battery also shows as a low
  battery on the accessory, which is what you actually wanted to know.

Closing this because the cause is gone from the code rather than because anyone
re-tested it — the thread is four years old. @MikeMighty, if you are still
running the plugin and still see it, please reopen.
